# Generated by Django 5.2.6 on 2026-03-12 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=150)),
                ('nombre_historia', models.CharField(max_length=255)),
                ('history_id', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ganador', models.CharField(blank=True, choices=[('spades', 'SPAdes'), ('velvet', 'Velvet')], max_length=20, null=True)),
                ('n50_spades', models.FloatField(blank=True, null=True)),
                ('l50_spades', models.FloatField(blank=True, null=True)),
                ('n50_velvet', models.FloatField(blank=True, null=True)),
                ('l50_velvet', models.FloatField(blank=True, null=True)),
                ('duracion_total', models.IntegerField(blank=True, null=True)),
                ('reporte_fastqc_r1_inicial', models.FileField(blank=True, null=True, upload_to='reportes/fastqc/')),
                ('reporte_fastqc_r2_inicial', models.FileField(blank=True, null=True, upload_to='reportes/fastqc/')),
                ('reporte_fastqc_r1_final', models.FileField(blank=True, null=True, upload_to='reportes/fastqc/')),
                ('reporte_fastqc_r2_final', models.FileField(blank=True, null=True, upload_to='reportes/fastqc/')),
                ('reporte_quast_spades', models.FileField(blank=True, null=True, upload_to='reportes/quast/')),
                ('reporte_quast_velvet', models.FileField(blank=True, null=True, upload_to='reportes/quast/')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
